# -*- coding: utf-8 -*-
"""DensidadEnergia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgFb4BLY_zaJTjxYPamXpTYfGuhTqu4U
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import find_peaks

def plot_and_analyze_stored_energy(file_name):
    """
    Carga, grafica y analiza los datos de energía almacenada,
    identificando los 3 picos más altos.
    """
    print(f"--- Leyendo el archivo: {file_name} ---")

    try:
        # Cargar los datos
        df = pd.read_csv(
            file_name,
            comment='%',
            sep='\s+',
            header=None,
            names=['Frecuencia_GHz', 'Energia_Almacenada_J']
        )
        print("¡Archivo cargado y procesado con éxito!")

        # --- ANÁLISIS DE PICOS ---
        # Usamos find_peaks de SciPy para encontrar todos los máximos locales.
        # 'height=1e-10' asegura que solo detectemos picos significativos, no ruido.
        peak_indices, _ = find_peaks(df['Energia_Almacenada_J'], height=1e-10)

        # Crear una lista de los picos encontrados
        all_peaks = []
        for index in peak_indices:
            freq = df.loc[index, 'Frecuencia_GHz']
            energy = df.loc[index, 'Energia_Almacenada_J']
            all_peaks.append((energy, freq))

        # Ordenar la lista de picos de mayor a menor energía
        all_peaks.sort(key=lambda x: x[0], reverse=True)

        # Imprimir los 3 picos más altos
        print("\n--- ANÁLISIS DE RESONANCIAS PRINCIPALES ---")
        print("Los 3 picos de Energía Almacenada más altos son:")
        print(f"{'Ranking':<10} {'Frecuencia (GHz)':<20} {'Energía Almacenada (J)':<25}")
        print("-" * 60)
        for i, (energy, freq) in enumerate(all_peaks[:3]):
            print(f"#{i+1:<9} {freq:<20.3f} {energy:.4e}")


        # --- Creación de la Gráfica ---
        plt.style.use('seaborn-v0_8-whitegrid')
        fig, ax = plt.subplots(figsize=(15, 8))

        ax.plot(df['Frecuencia_GHz'], df['Energia_Almacenada_J'],
                 linestyle='-',
                 linewidth=2.0,
                 color='green',
                 label='Energía Almacenada Total')

        ax.set_title('Energía Almacenada en la Cavidad vs. Frecuencia', fontsize=18, fontweight='bold')
        ax.set_xlabel('Frecuencia (GHz)', fontsize=14)
        ax.set_ylabel('Energía Almacenada (J)', fontsize=14)
        ax.legend(fontsize=12)
        ax.set_xlim(df['Frecuencia_GHz'].min(), df['Frecuencia_GHz'].max())
        ax.set_ylim(bottom=0)

        ax.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
        ax.tick_params(axis='both', which='major', labelsize=12)

        # Anotar solo el pico más alto en la gráfica para no saturarla
        if all_peaks:
            max_energy, max_freq = all_peaks[0]
            ax.annotate(f'Máxima Energía Almacenada\n{max_energy:.2e} J @ {max_freq:.2f} GHz',
                         xy=(max_freq, max_energy),
                         xytext=(max_freq + 0.5, max_energy * 0.8),
                         arrowprops=dict(facecolor='black', shrink=0.05, width=1.5, headwidth=10),
                         fontsize=12, fontweight='bold',
                         bbox=dict(boxstyle="round,pad=0.5", fc="lightgreen", ec="black", lw=1, alpha=0.8))

        plt.tight_layout()
        plt.show()

    except FileNotFoundError:
        print(f"\nERROR: No se encontró el archivo '{file_name}'")
    except Exception as e:
        print(f"\nOcurrió un error inesperado: {e}")

# --- Nombre del archivo ---
nombre_del_archivo = "DensidadEnergia.txt"
plot_and_analyze_stored_energy(nombre_del_archivo)